apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Ensures it binds with PVC without storageClass
  hostPath:
    path: "/home/akhil/postgres"

