apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090        # Prometheus internal port
      targetPort: 9090   # Prometheus container port
      nodePort: 30090    # NodePort to access Prometheus externally
  type: NodePort       # Expose the service via NodePort

