apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: monitoring
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: akhileshpatel123/react-app:v2  # Uise a specific version instead of 'latest'
          imagePullPolicy: Always  # Ensures the latest image is pulled every time
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Change this if needed

