apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: monitoring
spec:
  type: NodePort  # ✅ Change to LoadBalancer if needed
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32080
  - name: agent
    port: 50000
    targetPort: 50000
    nodePort: 32500
  selector:
    app: jenkins

